"""Transport-shape dataclasses for the inter-layer pipeline.

Lightweight (no validation) — flow in tight loops. For contract-enforced
types (CrossViewLink, TrajectoryPrediction, Anomaly), see the other modules
in this package.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, Optional

import numpy as np


@dataclass
class Frame:
    """A single decoded video frame plus per-view metadata.

    `telemetry` is None in v0.x. When L0 has access to GPS / IMU / gimbal
    feeds (v2+), populate with a dict of those values. The §3.4 #1 interface
    stub + smoke test guarantee downstream consumers handle None without
    breaking.
    """

    view_id: str
    t: float                              # unix timestamp seconds
    image: np.ndarray                     # H × W × 3 uint8 BGR (OpenCV)
    telemetry: Optional[dict] = None      # 🔌 §3.4 #1


@dataclass
class NLQuery:
    """Natural-language input to L6 (Mode A)."""

    text: str
    source: str = "text"                  # "text" | "voice"  (voice is 🔌 §3.4 #7)


@dataclass
class Event:
    """A semantic event produced by L3 or aggregated for Mode B briefing."""

    event_id: str
    type: str
    t: float
    view_id: str
    tracklet_ids: list[str] = field(default_factory=list)
    summary_text: str = ""


@dataclass
class Briefing:
    """Mode B output (v2 implementation; stub for now per §3.4 #6)."""

    t_start: float
    t_end: float
    tldr: str
    events: list[Event] = field(default_factory=list)
    cross_view_insights: list[str] = field(default_factory=list)


@dataclass
class ViewObservation:
    """L1→L2 boundary record: one tracked target observed at one timestamp in one view.

    `bbox` is normalized to [0, 1] in both axes (x1, y1, x2, y2 fractions of
    image width/height). Caller is responsible for normalization so L2 stays
    image-resolution-agnostic.

    `appearance_embedding` (M2.8) is an optional L2-normalized 768-d ReID
    vector for this bbox crop (typically from Qwen3-VL-Embedding-8B).
    When present on both sides of a Hungarian-matched pair, the L2 linker
    can use cosine similarity as a secondary identity filter
    (PROBLEMS P1-03 修法草案 #2).

    `segment_idx` (M3.0) — which segment of the source this observation
    came from. Required by `AppearanceCrossViewLinker` (appearance mode)
    for bucketing across non-synchronized videos; ignored by
    `GeometricCrossViewLinker` (synchronized mode buckets by `t` instead).

    `roi_uri` / `frame_idx` / `source_uri` (M4.1) — three pointers that let
    `LLMCrossViewLinker` load the ROI image at fallback time. All Optional
    so callers that don't need LLM cross-view linking can omit them.
      - `roi_uri`: path to a pre-cached JPEG of the bbox crop (ingest writes
        this when `--cache-rois` is ON; cheap 5-20ms imread at LLM-call time).
      - `frame_idx`: source frame index — used for the delayed-decode
        fallback when `roi_uri` is missing (50-200ms cv2.VideoCapture seek
        on mp4, 5-20ms on PNG sequences).
      - `source_uri`: parent video / image-dir path that `frame_idx`
        indexes into. Identical to `seg.source_uri` in `mva ingest`.
    """

    view_id: str
    tracklet_id: str
    t: float
    bbox: tuple[float, float, float, float]   # normalized [0,1] (x1, y1, x2, y2)
    class_name: str
    appearance_embedding: Optional[list[float]] = None
    segment_idx: Optional[int] = None
    roi_uri: Optional[str] = None              # 🔌 M4.1 — ROI cache hit path
    frame_idx: Optional[int] = None            # 🔌 M4.1 — delayed-decode source frame
    source_uri: Optional[str] = None           # 🔌 M4.1 — parent video/image-dir path


@dataclass
class Attachment:
    """A user-provided multimodal attachment that travels with a query.

    Generated by the CLI (`mva ask --image foo.jpg`), a future UI (file
    upload), or any other entry point. Loaders read from `path` lazily —
    the UI is responsible for spooling uploaded bytes to a temp file
    before constructing the Attachment.
    """

    kind: Literal["image", "video"]
    path: Path
    label: str = ""


@dataclass
class RichQuery:
    """User's full query: NL text plus optional multimodal attachments.

    A bare `str` question is equivalent to `RichQuery(text=str)`. The L6
    Orchestrator accepts either form — `RichQuery` is the canonical
    in-process representation. NLQuery stays as the input-source-tagged
    legacy contract for §3.4 #7 (voice input).
    """

    text: str
    attachments: list[Attachment] = field(default_factory=list)
    source: Literal["text", "voice"] = "text"
